version: 2
jobs:
  build:
    working_directory: ~/flights

    docker:
      # specify the version you desire here
      - image: circleci/node:12.16.1

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-cache

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy -v

      - save_cache:
          paths:
            - node_modules
          key: dependencies-cache-{{ checksum "package.json" }}